//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:13:29 AM BST 
//


package com.worldpay.servicing.gateway.outbound.model.approveservice;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for approval complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="approval"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PositionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="approvalItem" type="{http://www.siebel.com/xml/approvalCheckRequest}approvalItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="approvalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "approval", propOrder = {
    "caseId",
    "createdBy",
    "positionName",
    "approvalItem",
    "error",
    "approvalId"
})
public class Approval {

  protected String caseId;

  @XmlElement(required = true)
  protected String createdBy;

  @XmlElement(name = "PositionName")
  protected String positionName;

  protected List<ApprovalItem> approvalItem;

  protected String error;

  protected String approvalId;

  /**
   * Gets the value of the caseId property.
   *
   * @return possible object is {@link String }
   */
  public String getCaseId() {
    return caseId;
  }

  /**
   * Sets the value of the caseId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCaseId(String value) {
    this.caseId = value;
  }

  /**
   * Gets the value of the createdBy property.
   *
   * @return possible object is {@link String }
   */
  public String getCreatedBy() {
    return createdBy;
  }

  /**
   * Sets the value of the createdBy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCreatedBy(String value) {
    this.createdBy = value;
  }

  /**
   * Gets the value of the positionName property.
   *
   * @return possible object is {@link String }
   */
  public String getPositionName() {
    return positionName;
  }

  /**
   * Sets the value of the positionName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPositionName(String value) {
    this.positionName = value;
  }

  /**
   * Gets the value of the approvalItem property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
   * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the approvalItem property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getApprovalItem().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link ApprovalItem }
   */
  public List<ApprovalItem> getApprovalItem() {
    if (approvalItem == null) {
      approvalItem = new ArrayList<ApprovalItem>();
    }
    return this.approvalItem;
  }

  /**
   * Gets the value of the error property.
   *
   * @return possible object is {@link String }
   */
  public String getError() {
    return error;
  }

  /**
   * Sets the value of the error property.
   *
   * @param value allowed object is {@link String }
   */
  public void setError(String value) {
    this.error = value;
  }

  /**
   * Gets the value of the approvalId property.
   *
   * @return possible object is {@link String }
   */
  public String getApprovalId() {
    return approvalId;
  }

  /**
   * Sets the value of the approvalId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setApprovalId(String value) {
    this.approvalId = value;
  }

}
