//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:13:29 AM BST 
//


package com.worldpay.servicing.gateway.outbound.model.approveservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for approvalCheckRequestTopElmt complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="approvalCheckRequestTopElmt"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="approvalCheckRequest" type="{http://www.siebel.com/xml/approvalCheckRequest}approvalCheckRequest"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "approvalCheckRequestTopElmt", propOrder = {
    "approvalCheckRequest"
})
public class ApprovalCheckRequestTopElmt {

  @XmlElement(required = true)
  protected ApprovalCheckRequest approvalCheckRequest;

  /**
   * Gets the value of the approvalCheckRequest property.
   *
   * @return possible object is {@link ApprovalCheckRequest }
   */
  public ApprovalCheckRequest getApprovalCheckRequest() {
    return approvalCheckRequest;
  }

  /**
   * Sets the value of the approvalCheckRequest property.
   *
   * @param value allowed object is {@link ApprovalCheckRequest }
   */
  public void setApprovalCheckRequest(ApprovalCheckRequest value) {
    this.approvalCheckRequest = value;
  }

}
