//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:13:29 AM BST 
//


package com.worldpay.servicing.gateway.outbound.model.approveservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for approvalItem complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="approvalItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="service" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="serviceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="serviceClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="serviceItemType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creditDebit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "approvalItem", propOrder = {
    "service",
    "serviceId",
    "serviceClass",
    "serviceItemType",
    "amount",
    "currency",
    "creditDebit"
})
public class ApprovalItem {

  protected String service;

  protected String serviceId;

  protected String serviceClass;

  @XmlElement(required = true)
  protected String serviceItemType;

  protected String amount;

  protected String currency;

  protected String creditDebit;

  /**
   * Gets the value of the service property.
   *
   * @return possible object is {@link String }
   */
  public String getService() {
    return service;
  }

  /**
   * Sets the value of the service property.
   *
   * @param value allowed object is {@link String }
   */
  public void setService(String value) {
    this.service = value;
  }

  /**
   * Gets the value of the serviceId property.
   *
   * @return possible object is {@link String }
   */
  public String getServiceId() {
    return serviceId;
  }

  /**
   * Sets the value of the serviceId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setServiceId(String value) {
    this.serviceId = value;
  }

  /**
   * Gets the value of the serviceClass property.
   *
   * @return possible object is {@link String }
   */
  public String getServiceClass() {
    return serviceClass;
  }

  /**
   * Sets the value of the serviceClass property.
   *
   * @param value allowed object is {@link String }
   */
  public void setServiceClass(String value) {
    this.serviceClass = value;
  }

  /**
   * Gets the value of the serviceItemType property.
   *
   * @return possible object is {@link String }
   */
  public String getServiceItemType() {
    return serviceItemType;
  }

  /**
   * Sets the value of the serviceItemType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setServiceItemType(String value) {
    this.serviceItemType = value;
  }

  /**
   * Gets the value of the amount property.
   *
   * @return possible object is {@link String }
   */
  public String getAmount() {
    return amount;
  }

  /**
   * Sets the value of the amount property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAmount(String value) {
    this.amount = value;
  }

  /**
   * Gets the value of the currency property.
   *
   * @return possible object is {@link String }
   */
  public String getCurrency() {
    return currency;
  }

  /**
   * Sets the value of the currency property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCurrency(String value) {
    this.currency = value;
  }

  /**
   * Gets the value of the creditDebit property.
   *
   * @return possible object is {@link String }
   */
  public String getCreditDebit() {
    return creditDebit;
  }

  /**
   * Sets the value of the creditDebit property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCreditDebit(String value) {
    this.creditDebit = value;
  }

}
