//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:13:29 AM BST 
//


package com.worldpay.servicing.gateway.outbound.model.approveservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for approvalCheckRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="approvalCheckRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="callInfo" type="{http://www.siebel.com/xml/approvalCheckRequest}callInfo"/&gt;
 *         &lt;element name="approval" type="{http://www.siebel.com/xml/approvalCheckRequest}approval"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "approvalCheckRequest", propOrder = {
    "callInfo",
    "approval"
})
public class ApprovalCheckRequest {

  @XmlElement(required = true)
  protected CallInfo callInfo;

  @XmlElement(required = true)
  protected Approval approval;

  /**
   * Gets the value of the callInfo property.
   *
   * @return possible object is {@link CallInfo }
   */
  public CallInfo getCallInfo() {
    return callInfo;
  }

  /**
   * Sets the value of the callInfo property.
   *
   * @param value allowed object is {@link CallInfo }
   */
  public void setCallInfo(CallInfo value) {
    this.callInfo = value;
  }

  /**
   * Gets the value of the approval property.
   *
   * @return possible object is {@link Approval }
   */
  public Approval getApproval() {
    return approval;
  }

  /**
   * Sets the value of the approval property.
   *
   * @param value allowed object is {@link Approval }
   */
  public void setApproval(Approval value) {
    this.approval = value;
  }

}
