//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:13:29 AM BST 
//


package com.worldpay.servicing.gateway.outbound.model.approveservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for callInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="callInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="callId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="callType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "callInfo", propOrder = {
    "callId",
    "callType",
    "description",
    "creationDate"
})
public class CallInfo {

  protected String callId;

  protected String callType;

  protected String description;

  protected String creationDate;

  /**
   * Gets the value of the callId property.
   *
   * @return possible object is {@link String }
   */
  public String getCallId() {
    return callId;
  }

  /**
   * Sets the value of the callId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCallId(String value) {
    this.callId = value;
  }

  /**
   * Gets the value of the callType property.
   *
   * @return possible object is {@link String }
   */
  public String getCallType() {
    return callType;
  }

  /**
   * Sets the value of the callType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCallType(String value) {
    this.callType = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the creationDate property.
   *
   * @return possible object is {@link String }
   */
  public String getCreationDate() {
    return creationDate;
  }

  /**
   * Sets the value of the creationDate property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCreationDate(String value) {
    this.creationDate = value;
  }

}
