//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:12:18 AM BST 
//


package com.worldpay.servicing.gateway.inbound.model.approvews;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.worldpay.servicing.gateway.inbound.model.approvews package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived
 * interfaces and classes representing the binding of schema type definitions, element declarations and model groups.  Factory methods for
 * each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
   * com.worldpay.servicing.gateway.inbound.model.approvews
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link ServicingItemRequest }
   */
  public ServicingItemRequest createServicingItemRequest() {
    return new ServicingItemRequest();
  }

  /**
   * Create an instance of {@link ApproveServicingItemRequest }
   */
  public ApproveServicingItemRequest createApproveServicingItemRequest() {
    return new ApproveServicingItemRequest();
  }

  /**
   * Create an instance of {@link ApproveServicingItemResponse }
   */
  public ApproveServicingItemResponse createApproveServicingItemResponse() {
    return new ApproveServicingItemResponse();
  }

  /**
   * Create an instance of {@link ServicingItemResponse }
   */
  public ServicingItemResponse createServicingItemResponse() {
    return new ServicingItemResponse();
  }

  /**
   * Create an instance of {@link ServicingItemRequest.CallInfo }
   */
  public ServicingItemRequest.CallInfo createServicingItemRequestCallInfo() {
    return new ServicingItemRequest.CallInfo();
  }

  /**
   * Create an instance of {@link ServicingItemRequest.CaseInformation }
   */
  public ServicingItemRequest.CaseInformation createServicingItemRequestCaseInformation() {
    return new ServicingItemRequest.CaseInformation();
  }

  /**
   * Create an instance of {@link ServicingItemRequest.ServiceItem }
   */
  public ServicingItemRequest.ServiceItem createServicingItemRequestServiceItem() {
    return new ServicingItemRequest.ServiceItem();
  }

}
