//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:12:18 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://model.inbound.gateway.servicing.worldpay.com/approvews", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.worldpay.servicing.gateway.inbound.model.approvews;
