//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:12:18 AM BST 
//


package com.worldpay.servicing.gateway.inbound.model.approvews;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceItemStatus.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="serviceItemStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="APPROVED"/&gt;
 *     &lt;enumeration value="NOT_APPROVED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "serviceItemStatus")
@XmlEnum
public enum ServiceItemStatus {

  APPROVED,
  NOT_APPROVED;

  public static ServiceItemStatus fromValue(String v) {
    return valueOf(v);
  }

  public String value() {
    return name();
  }

}
