//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:12:18 AM BST 
//


package com.worldpay.servicing.gateway.inbound.model.approvews;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceItemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="serviceItemType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Adjustment"/&gt;
 *     &lt;enumeration value="Payment"/&gt;
 *     &lt;enumeration value="AdhocCharge"/&gt;
 *     &lt;enumeration value="BillCorrection"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "serviceItemType")
@XmlEnum
public enum ServiceItemType {

    @XmlEnumValue("Adjustment")
    ADJUSTMENT("Adjustment"),
    @XmlEnumValue("Payment")
    PAYMENT("Payment"),
    @XmlEnumValue("AdhocCharge")
    ADHOC_CHARGE("AdhocCharge"),
    @XmlEnumValue("BillCorrection")
    BILL_CORRECTION("BillCorrection");
    private final String value;

    ServiceItemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceItemType fromValue(String v) {
        for (ServiceItemType c: ServiceItemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
