//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 10:12:18 AM BST 
//


package com.worldpay.servicing.gateway.inbound.model.approvews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for servicingItemResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="servicingItemResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="requestStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "servicingItemResponse", propOrder = {
    "id",
    "requestStatus",
    "errorMessage"
})
public class ServicingItemResponse {

  @XmlElement(required = true)
  protected String id;

  @XmlElement(required = true)
  protected String requestStatus;

  @XmlElement(required = true)
  protected String errorMessage;

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the requestStatus property.
   *
   * @return possible object is {@link String }
   */
  public String getRequestStatus() {
    return requestStatus;
  }

  /**
   * Sets the value of the requestStatus property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRequestStatus(String value) {
    this.requestStatus = value;
  }

  /**
   * Gets the value of the errorMessage property.
   *
   * @return possible object is {@link String }
   */
  public String getErrorMessage() {
    return errorMessage;
  }

  /**
   * Sets the value of the errorMessage property.
   *
   * @param value allowed object is {@link String }
   */
  public void setErrorMessage(String value) {
    this.errorMessage = value;
  }

}
