//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.21 at 02:15:02 PM BST 
//


package com.worldpay.servicing.gateway.outbound.model.partyhierarchy;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.worldpay.servicing.gateway.outbound.model.partyhierarchy package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived
 * interfaces and classes representing the binding of schema type definitions, element declarations and model groups.  Factory methods for
 * each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _SEARCHEDPARTY_QNAME = new QName("http://www.siebel.com/xml/WP%20ORMB%20Party%20Response%20IO",
      "SEARCHED_PARTY");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
   * com.worldpay.servicing.gateway.outbound.model.partyhierarchy
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link SEARCHEDPARTY }
   */
  public SEARCHEDPARTY createSEARCHEDPARTY() {
    return new SEARCHEDPARTY();
  }

  /**
   * Create an instance of {@link SEARCHEDPARTYTopElmt }
   */
  public SEARCHEDPARTYTopElmt createSEARCHEDPARTYTopElmt() {
    return new SEARCHEDPARTYTopElmt();
  }

  /**
   * Create an instance of {@link PARTY }
   */
  public PARTY createPARTY() {
    return new PARTY();
  }

  /**
   * Create an instance of {@link WpHierQueryInput }
   */
  public WpHierQueryInput createWpHierQueryInput() {
    return new WpHierQueryInput();
  }

  /**
   * Create an instance of {@link WpHierQueryOutput }
   */
  public WpHierQueryOutput createWpHierQueryOutput() {
    return new WpHierQueryOutput();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link SEARCHEDPARTY }{@code >}
   *
   * @param value Java instance representing xml element's value.
   * @return the new instance of {@link JAXBElement }{@code <}{@link SEARCHEDPARTY }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.siebel.com/xml/WP%20ORMB%20Party%20Response%20IO", name = "SEARCHED_PARTY")
  public JAXBElement<SEARCHEDPARTY> createSEARCHEDPARTY(SEARCHEDPARTY value) {
    return new JAXBElement<SEARCHEDPARTY>(_SEARCHEDPARTY_QNAME, SEARCHEDPARTY.class, null, value);
  }

}
