//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.21 at 02:15:02 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.siebel.com/xml/WP%20ORMB%20Party%20Response%20IO", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.worldpay.servicing.gateway.outbound.model.partyhierarchy;
