//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.21 at 02:15:02 PM BST 
//


package com.worldpay.servicing.gateway.outbound.model.partyhierarchy;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SEARCHED_PARTY complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SEARCHED_PARTY"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MASTER_PARTY_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ERR_MSG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ERR_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EXTERNAL_MERCHANT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PARTY" type="{http://www.siebel.com/xml/WP%20ORMB%20Party%20Response%20IO}PARTY" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SEARCHED_PARTY", propOrder = {
    "masterpartyid",
    "errmsg",
    "errcode",
    "externalmerchantid",
    "party"
})
public class SEARCHEDPARTY {

  @XmlElement(name = "MASTER_PARTY_ID")
  protected String masterpartyid;

  @XmlElement(name = "ERR_MSG")
  protected String errmsg;

  @XmlElement(name = "ERR_CODE")
  protected String errcode;

  @XmlElement(name = "EXTERNAL_MERCHANT_ID")
  protected String externalmerchantid;

  @XmlElement(name = "PARTY")
  protected List<PARTY> party;

  /**
   * Gets the value of the masterpartyid property.
   *
   * @return possible object is {@link String }
   */
  public String getMASTERPARTYID() {
    return masterpartyid;
  }

  /**
   * Sets the value of the masterpartyid property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMASTERPARTYID(String value) {
    this.masterpartyid = value;
  }

  /**
   * Gets the value of the errmsg property.
   *
   * @return possible object is {@link String }
   */
  public String getERRMSG() {
    return errmsg;
  }

  /**
   * Sets the value of the errmsg property.
   *
   * @param value allowed object is {@link String }
   */
  public void setERRMSG(String value) {
    this.errmsg = value;
  }

  /**
   * Gets the value of the errcode property.
   *
   * @return possible object is {@link String }
   */
  public String getERRCODE() {
    return errcode;
  }

  /**
   * Sets the value of the errcode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setERRCODE(String value) {
    this.errcode = value;
  }

  /**
   * Gets the value of the externalmerchantid property.
   *
   * @return possible object is {@link String }
   */
  public String getEXTERNALMERCHANTID() {
    return externalmerchantid;
  }

  /**
   * Sets the value of the externalmerchantid property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEXTERNALMERCHANTID(String value) {
    this.externalmerchantid = value;
  }

  /**
   * Gets the value of the party property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
   * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the party property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getPARTY().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link PARTY }
   */
  public List<PARTY> getPARTY() {
    if (party == null) {
      party = new ArrayList<PARTY>();
    }
    return this.party;
  }

}
