//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.21 at 02:15:02 PM BST 
//


package com.worldpay.servicing.gateway.outbound.model.partyhierarchy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.siebel.com/xml/WP%20ORMB%20Party%20Response%20IO}SEARCHED_PARTY"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchedparty"
})
@XmlRootElement(name = "wp_hier_query_Output", namespace = "http://siebel.com/CustomUI")
public class WpHierQueryOutput {

  @XmlElement(name = "SEARCHED_PARTY", required = true)
  protected SEARCHEDPARTY searchedparty;

  /**
   * Gets the value of the searchedparty property.
   *
   * @return possible object is {@link SEARCHEDPARTY }
   */
  public SEARCHEDPARTY getSEARCHEDPARTY() {
    return searchedparty;
  }

  /**
   * Sets the value of the searchedparty property.
   *
   * @param value allowed object is {@link SEARCHEDPARTY }
   */
  public void setSEARCHEDPARTY(SEARCHEDPARTY value) {
    this.searchedparty = value;
  }

}
