package com.worldpay.servicing.model.dto.enums;

public enum CacheType {
  SERVICE,
  SERVICING_ADMIN_RULE,
  ORIGINATING_BANK_ACCOUNT,
  PAYMENT_CHANNEL,
  SERVICE_CLASSIFIER,
  SERVICE_ITEM_HIERARCHY,
  CURRENCY,
  APPROVAL_STATUS,
  ACCOUNT_SUBACCOUNT_MAPPING,
  BILL_CORRECTION_REASONS,
  APP_PARAM,
  SETTLEMENT_GROUP,
  PRICING
}
